### PR TITLE
Support LOS 15.1

### PR DESCRIPTION
**Pull request by Zap0tec**
Added support for Lineage OS 15.1. Tested and working without errors on my phone (Redmi Note 4 mido).

### CODE REVIEW

**Comment by rickysarraf** [comment]
Is there a way I could test this on my phone?

**Comment by iptux** [comment]
I have uploaded apk with this pull included. [Link](https://drop.me/M8mWKQ)

Signature may different, uninstall first and then install.

Please feedback with device model, ROM info and whether the module is working or not.

**Comment by rickysarraf** [comment]
@iptux that APK does not install

**Comment by rickysarraf** [comment]
My bad. I didn't realize that my previous installation of XCallRecording was still there in Xposed. After removing it, and then installing the test apk, it is working perfect.

Hardware: Redmi Note 4
OS: Lineage OS 15.1

Thank you @iptux @Zap0tec

**Comment by gxacker** [comment]
Hi! Xiaomi mi5/gemini, LOS15.1. Did not work automatic start recording. Try increase delay up to 2sec - did not help.

**Comment by Zap0tec** [comment]
Which build of Linege OS are you using? Is manual recording by clicking the button works fine?

**Comment by gxacker** [comment]
2018-08-13. Manual recording works fine.

**Comment by gxacker** [comment]
Updating to nightly 20aug is solved my problem.

**Pull request merged**
